### ISSUE TITLE
custom fields: can we avoid the config overwrite?

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#1004]
- related to https://github.com/inveniosoftware/invenio-records-resources/issues/360

```python
class CustomFieldsServiceConfig(Schema):
    """Configuration for the Custom Fields service."""

    fields_config_var = "RDM_RECORDS_CUSTOM_FIELDS"
```

feels very ad-hoc. Is there another way of using diff field from config for records and communities?

**Comment by zzacharo** [comment]
That's outdated due to the latest changes
