### ISSUE TITLE
review lazyness usage on attributes and which level it is implemented on

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#1029]
Needs to be lazy loaded due to:

- This field is added to `relations` <[inveniosoftware/invenio-rdm-records#1021](https://github.com/inveniosoftware/invenio-rdm-records/pull/1021/files#diff-5d1307e2e4f0dc8f18dff697e272b141a20ce79d1017b2f7771c51740123beeeR208>), since it is a class attr it will be initialized before app context.
- This will initialize the field here https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/records/systemfields/relations.py#L31 (I know it's lazy there buuuut....)
- here it gets called https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/systemfields/relations/field.py#L130 which happens on initialization of the field. So even if at vocabularies level is lazy, invenio-records does the call.

NOTE: I do not like making a change below the chaing (invenio-records) because of a problem higher up (invenio-rdm-records, invenio-vocabularies). However, I do not see any other solution (open to ideas). I've tried making a LocalProxy the `record.relations` field in `invenio-rdm-records...api.py`, however, `LocalProxy` does not implement `__get__` and then we get into troubles with the descriptor behaviour of `RelationsFields` and it breaks (returns a RelationsFields instead of RelationsMapping when accessing `.obj`)

https://github.com/inveniosoftware/invenio-records/pull/296

**Comment by ppanero** [comment]
As a temporary measure the `_fields` have been made lazy in invenio-records. However, a solution needs to be found at invenio-rdm-records level. Moreover, the `LocalProxy` in invenio-vocabularies can be safely removed (I think). Options are:

- Made `_fields` into a property. Still not nice, because is because of an assumtion of a higher level module. Is more or less the same than making it lazy.
- Implement a custom `LocalProxy` that implements `__get__` so we can make the `Record.relations` field lazy.
- Others?

**Comment by zzacharo** [comment]
**NOTE**: Saving the form, filiing in a voacbualry field fails

**Comment by ppanero** [comment]
vocabulary failure fixed by https://github.com/inveniosoftware/invenio-records/pull/297
The `explode_fields()` was being called on each instantiation. Then, the cached was only injected on the first (since cached injection depends on obj caching). However, on subsequent calls the obj was taken from cached but the fields exploded again (loosing the inner cache).

Extra note: the fields were exploded 18 times per relation field. By caching the property we save many calls.

**Comment by ppanero** [comment]
This PR https://github.com/inveniosoftware/invenio-records/pull/298 partly addresses the problem. We remove the dependency with `LocalProxy`. However, we will still have some sort of "logic" change at `invenio-records` level due to the fact that higher up (rdm-records) some fields are meant to load from config.

There are three ways around this problem:
- Registry: However, this would have a big impact on the implementation
- Making Lazy the `relations` attribute at rdm-records level. Could be the correct implementation but seems a complex (see description of the issue).
- Since more than one `Relation` requires the `_fields` lazy laoding (`CustomFieldsRelation` in invenio-vocabularies, and This `MultiRelationField`), what about creating a mixin that enables this lazyness. We would be "supporting" lazy loading from a lower level. Alternatively, we could move the implementation to invenio-records-resources and just assume the technical dep of a not perfect implementation.

**Comment by ppanero** [comment]
IRL discussion: make it a property both on `RelationFields` and also in `Multi`. That way we disentangle form `LocalProxy`.
