### ISSUE TITLE
administration: Add formatting options to oai-set

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-records#1064]
![Screenshot 2022-09-20 at 10 53 04](https://user-images.githubusercontent.com/38131488/191213882-571d7ece-2f75-4fde-b0b1-4becaf3b604c.png)

In the links section we need a dropdown with a set of different exporting formats (check docs for extensive list) which will replace the metadataPrefix URL parameter of the List records and list identifiers links depending on the chosen format.
Default format option is oai_dc as currently visible.

**Comment by alejandromumo** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/21204744/191789185-986dd2d0-bc31-4024-a544-490d5839e212.png">
