### ISSUE TITLE
DNB requirement: need a single packed file of all content 

### ISSUE THREAD

**Issue by wgresshoff** [inveniosoftware/invenio-rdm-records#1104]
## Is your feature request related to a problem? Please describe.
The DNB (german national library) uses the OAI-PMH metadata formats to harvest URN's and metadata and content of the document repos of german libraries. If there is more than one file belonging to a document a zipped version of all the content is required (they accept only one transfer url).

## Describe the solution you'd like
Provide a worker to zip content. Add a marker in the file metadata to make the transfer file recognisable.

## Describe alternatives you've considered
Perhaps there is the possibility to do a on-the-fly compression while delivering the file. A virtual download URL to trigger the compression and download would be needed (it's CPU vs. space).

## Additional context
[xMetaDissPlus spec](https://www.dnb.de/EN/Professionell/Standardisierung/Standards/_content/xmdp.html)
[xepicur (german)]https://wiki.dnb.de/display/URNSERVDOK/xepicur+-+XML-Datentransferformat+zur+Verwaltung+von+URN

**Comment by chriz-uniba** [comment]
related: we would like to see a "Download all" button in the user-interface

**Comment by Herrner** [comment]
This _has_ to be a `.zip`? Because if not, this might also be a OCFL-usecase?

**Comment by Herrner** [comment]
> related: we would like to see a "Download all" button in the user-interface

See also: https://github.com/inveniosoftware/product-rdm/issues/86

**Comment by wgresshoff** [comment]
> This _has_ to be a `.zip`? Because if not, this might also be a OCFL-usecase?

No, it hasn't be a .zip, just phoned with DNB as here are no docs available ragarding this question. Allowed format are tar, tar.gz, .gz, .zip and .7z.

**Comment by Herrner** [comment]
...but it's still relevant when you look at [this](https://github.com/inveniosoftware/product-rdm/issues/86#issuecomment-1033643942) comment. I don't know how realistic this is, though.

**Comment by wgresshoff** [comment]
It depends largely on what exactly you want to achieve. The DNB just wants exactly one URL they can call to download all the content at once. That would also be a sufficient solution for [](https://github.com/inveniosoftware/product-rdm/issues/86) if you don't want to select what's in the download file beforehand.

**Comment by lnielsen** [comment]
See also proposed changes to DataCite v4.5 for the new distribution tag: https://datacite.org/documents/DataCite_Metadata_Schema_4.5_RFC.pdf
