### ISSUE TITLE
records: remove from community

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#1163]
This should be treated as an actions on the record endpoint (i.e. `/records/<pid_value>/actions`). That way the could be a similar payload for `add` and `remove`. For example:

```json
{
    "community_id": ...,
    "event": "add/remove",
}
```

**Comment by jrcastro2** [comment]
After disscussing with @ntarocco - who is implementing the submit to multiple records - we have agreed to the following:
- The endpoint is `api/records/<pid>/communities`.
  - POST **or** PUT action:  will accept a list of community ids.
  - DELETE action: will accept a list of community ids.

**Comment by ppanero** [comment]
missing PR in rdm-records
