### ISSUE TITLE
UI: Restricted community error on submitting for review

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-rdm-records#1167]
Package version (if known): V11

## Describe the bug
Testing on https://inveniordm.web.cern.ch/
It seems like there is a UI issue to reproduce:

## Steps to Reproduce
1. Create a restricted community -> Fill required fields -> Submit for review
2. See error: Record submitted to restricted community cannot be public.

## Expected behavior
Submit the record without errors

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/36583694/215597299-c0028eb7-6d80-47af-845d-ed2b239c2667.png)

## Additional context

To skip the error, you need to explicitly click on Visibility restricted so you be able to submit the record for review.

**Comment by fenekku** [comment]
I think this is related/the same: https://github.com/inveniosoftware/invenio-app-rdm/issues/1862

**Comment by Samk13** [comment]
Indeed, thank you for bringing it up @fenekku, I will close this one then.
