### ISSUE TITLE
Title with type MainTitle should be the displayed title

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#123]
Creating a record with a title type MainTitle should display that title on the landing page. Right now, the first title of titles is shown on the landing page.

Should there be 1 and only 1 MainTitle?

**Comment by lnielsen** [comment]
I'm closing this one, as the data model should have a primary title, which is the one being displayed so there's no ambiguity in which title to display.

**Comment by fenekku** [comment]
Just to be clear then: 

- the intent is to have the first title in the deposit list of titles be the one displayed on the record landing page
- this applies irrespective of whether that title is marked as MainTitle or not
- there is no check to prevent a record from having multiple MainTitles
