### ISSUE TITLE
custom fields: update deposit form

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-records#1232]
- [x] Custom field imprint is missing "book" field - compare with zenodo
- [x] Implement the agreed solution based on mockups
- [x] Update the deposit form
- [x] Update the landing page
- [x] Update the record's listing.   

**Updated mockups**

## Deposit form
![Image](https://user-images.githubusercontent.com/38131488/223471736-b3c59354-ad16-4afe-aefc-92cc9cbda338.png)

## Landing page
![image](https://user-images.githubusercontent.com/21204744/224312905-e6557d80-bc05-4f9e-9bff-fbc9209110fb.png)

## Record's listing
![image](https://user-images.githubusercontent.com/21204744/224312974-3bd94390-d8ef-4cd0-a534-b9dc8c6b0ad1.png)

**Comment by alejandromumo** [comment]
The field `imprint.title` is already implemented: https://github.com/inveniosoftware/invenio-rdm-records/blob/fd17d8d236312db85dd8316035e28d210175636f/invenio_rdm_records/contrib/imprint/custom_fields.py#L31

Is this issue about the UI element (e.g. label)?

**Comment by alejandromumo** [comment]
## Deposit form

![Screenshot at Mar 08 16-48-10](https://user-images.githubusercontent.com/21204744/223761902-346cbaba-de83-44c7-85dc-5e650894eb08.png)


![Screenshot at Mar 08 16-48-01](https://user-images.githubusercontent.com/21204744/223761912-0b3935e5-cf9b-4c1c-b46b-ff74e83e744a.png)

## Landing page


![Screenshot at Mar 10 11-20-00](https://user-images.githubusercontent.com/21204744/224290889-06f7986e-0b5f-452d-8673-1b4e00ca973e.png)


## Record listing

![Screenshot at Mar 10 11-11-56](https://user-images.githubusercontent.com/21204744/224289861-eefd77c8-46b2-49f8-bb9c-cc80f56949ff.png)

![Screenshot at Mar 10 11-12-23](https://user-images.githubusercontent.com/21204744/224289854-ed9d401a-0510-4075-b2d6-351f1e433cae.png)

**Comment by alejandromumo** [comment]
The current implementation creates a duplication in the UI:

![image](https://user-images.githubusercontent.com/21204744/224331518-70c4ab0d-8bdb-4fda-ad0e-c1baed89c93c.png)

This is going to be discussed with the team, in the meantime the issue will be moved to review.

**Comment by alejandromumo** [comment]
> The current implementation creates a duplication in the UI:
> 
> ![image](https://user-images.githubusercontent.com/21204744/224331518-70c4ab0d-8bdb-4fda-ad0e-c1baed89c93c.png)
> 
> This is going to be discussed with the team, in the meantime the issue will be moved to review.

We decided to remove the duplicated sections on the bottom. "How" is still to be experimented / decided, some suggestions are:

- Defining a variable "Hidden" (no show) to disable the section's rendering
- Empty jinja template (overriding) : to be confirmed if this works or not

**Comment by alejandromumo** [comment]
> > The current implementation creates a duplication in the UI:
> > ![image](https://user-images.githubusercontent.com/21204744/224331518-70c4ab0d-8bdb-4fda-ad0e-c1baed89c93c.png)
> > This is going to be discussed with the team, in the meantime the issue will be moved to review.
> 
> We decided to remove the duplicated sections on the bottom. "How" is still to be experimented / decided, some suggestions are:
> 
>     * Defining a variable "Hidden" (no show) to disable the section's rendering
> 
>     * Empty jinja template (overriding) : to be confirmed if this works or not

For the empty jinja option: my suspicions are confirmed - the fields are not rendered but the section's tab "Publishing information" is still displayed. Therefore it's not an option for now.

**Comment by alejandromumo** [comment]
>     * Defining a variable "Hidden" (no show) to disable the section's rendering
> 

Implemented this option, for now. If we move forward with this solution, it **MUST** be documented for custom fields.

Updated screenshot: 

![image](https://user-images.githubusercontent.com/21204744/225050687-b993c683-bae3-47f2-b098-14d1bd30ce37.png)
