### ISSUE TITLE
Generate new empty record for deposit page

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#125]
When depositing a new record, formik needs initial values and react wants controlled form values to not be null/undefined. We have established that formik keeps `form.initialValues` and `form.values` distinct so we can use a diff between the 2 to know what changed. This means we can use empty strings as initial values and satisfy the requirements from formik and react.

How we generate those empty strings is up for discussion:

1) Have the backend do it
2) Have the frontend do it

**Option 1): Have the backend do it**

Pro: Backend already knows about the data model so it can generate empty string initial values easily.
Cons: ideally backend shouldn't do things because a frontend needs it i.e. tie itself to a frontend implementation. Other applications that would use the API wouldn't have access to this trick since it is not exposed via an API.  

**Option 2) Have the frontend do it**
Pros: It is the frontend's responsibility. Defaults are very much tied to the UI/UX so it makes sense to be controlled by the frontend.  
Cons: The frontend would need to duplicate the model completely and keep it in sync with the backend model: not as easy as having it auto-generated by the backend. (Technically the frontend already knows about the model anyway since the form's Field components are tightly coupled with it)

Which approach do other devs / architects prefer?

**Comment by fenekku** [comment]
More and more experience with formik/react in the frontend points to having the frontend deal with initial empty record. Having the backend pass `{}` for new record and `{"id": ..., ,,,}` for saved record is the way to go.

**Comment by lnielsen** [comment]
I'm closing this issue as there hasn't been any discussion on this issue lately, and it seems we've reached and acceptable solution at this point.
