### ISSUE TITLE
pids: navigating to `/records/{parent_pid}` gives a 500

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#1282]
## Steps to Reproduce

1. Publish a record
2. Navigate to `/records/{parent_pid}` (where `parent_pid` is the parent PID of the published record)
3. See a "500 Internal server error" page
4. (Bonus): The equivalent REST API endpoint, i.e. `/api/records/{parent_pid}` returns a 404 response

## Expected behavior

- You should be redirected to the latest version of the record

**Comment by slint** [comment]
The implementation in https://github.com/inveniosoftware/invenio-drafts-resources/pull/237, https://github.com/inveniosoftware/invenio-rdm-records/pull/1370, and https://github.com/inveniosoftware/invenio-app-rdm/pull/2310 relies on retrying to resolve the object ID that a recid/DOI PID points as a parent record and from there resolving the latest published record version.

An alternative solution is to rely on PID redirects, i.e. constantly updating the parent recid and DOI to point to the equivalent latest record version PID. Some pros/cons:

- :+1: This would rely on just handling the `invenio_pidstore.errors.PIDRedirectedError` gracefully and redirecting from there. This is also "semantically" a bit more correct based on the data model we already have.
- :-1: We lose the direct reference of the parent PID's `object_uuid` to the parent record ID. This might be needed at some point if we plan to put up a dedicated landing page for the parent PID.
- :-1: Needs a potentially difficult data migration recipe that will change the `object_uuid` and `status` of all parent PIDs.

WDYT @zzacharo @ntarocco @kpsherva @ppanero? (just picked you four, since you might have some context on the task and PIDs in general)

**Comment by ntarocco** [comment]
I agree with your solution! :) Thanks for explanation!
