### ISSUE TITLE
config: THEME_SITEURL does not come from invenio-theme but is used

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#131]
The config var `THEME_SITEURL` is used to set up the base url when working outside of a context (e.g. celery tasks). However:

1- The name is misleading, it has nothing to do with theming
2- It is not defined in invenio-theme

It appeared as a legacy from Zenodo code migration.

**Comment by fenekku** [comment]
This is being addressed in search work.
