### ISSUE TITLE
Cannot search for a custom field

### ISSUE THREAD

**Issue by treecon** [inveniosoftware/invenio-rdm-records#1352]
I have successfully created a custom field (with name "teams") based on this documentation: https://inveniordm.docs.cern.ch/develop/howtos/custom_fields/

The problem is that I cannot make a search using this field in the URL.
I have tried the following, among other tries:

https://127.0.0.1:5000/search?q=asd&l=list&p=1&s=10&sort=bestmatch&f=teams:myteam
https://127.0.0.1:5000/search?q=asd&l=list&p=1&s=10&sort=bestmatch&custom_fields=teams:myteam

Also, how can I add that field to the RDM search? I add 'teams' to the 'facets' property of RDM_SEARCH but an error occurs.

Can anybody help? Thank you!

**Comment by tmorrell** [comment]
If you haven't defined a namespace, you should be able to search with `custom_fields.teams:myteam`. Here is an example on the test system https://inveniordm.web.cern.ch/search?q=custom_fields.rdm%5C%3Arelease_number_of_lines%3A15&l=list&p=1&s=10&sort=bestmatch. The custom fields on the test system include a namespace, so additionally an escape on the colon between the namespace and the field is needed. 

There is a lot more configuration options for the custom fields available at https://inveniordm.docs.cern.ch/customize/metadata/custom_fields/records/

**Comment by tmorrell** [comment]
I'm closing this issue, but feel free to reopen if you're still having problems.
