### ISSUE TITLE
naming: resources

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#142]
As commented here: https://github.com/inveniosoftware/invenio-rdm-records/pull/139 and in many others.

- BlaBlaBlaRecordDraftResourceConfig, etc. are really long names. Shall we make `ResourceConfig` into an acronym? Otherwise shall we just call "Draft" and "Record".
- What is a `deposit`? Shall we use it? if so, does it mean "draft" or "draft+resource"?

**Comment by ppanero** [comment]
@fenekku @lnielsen @zzacharo This can be closed? I think we cleared out:

- Deposit won't be used. Need name for draft+resource
- Acronyms won't be used, it's true that is long, they are clear.

**Comment by fenekku** [comment]
Here is my naming approach vote:

At the edge level (i.e. Authors, BibliographicRecords, Terms, Licenses...) just using `<Name>Service` (even if it inherits from draft service). For example: BibliographicRecordService is the service that deals with all functionalities for bibliographic records. 

For Resources, variations in naming that reflect the endpoints is fine by me. (reiterates value in creating resources that could combine action endpoints too...)

If nothing else to discuss, we can close.
