### ISSUE TITLE
Investigate update / put workflow

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#148]
**EDIT**
This bug report was reported on the June release. This task should be about testing if this is still the case in the August release. If it is update this task as such. Otherwise close it.

**Bug report**
From cswartz on discord:

1- Create a record
2- Update a field from the metadata and resubmit via PUT
Expect
3- valid update
Get
3- 400 data validation error without any more details

The data submitted was:

```json
{
  "_access": {
    "files_restricted": false,
    "metadata_restricted": false
  },
  "_created_by": 2,
  "_default_preview": "previewer one",
  "_internal_notes": [
    {
      "note": "RDM record",
      "timestamp": "1998-08-30",
      "user": "inveniouser"
    }
  ],
  "_owners": [
    1
  ],
  "access_right": "open",
  "contact": "info@inveniosoftware.org",
  "contributors": [
    {
      "affiliations": [
        {
          "identifiers": {
            "ror": "03yrm5c26"
          },
          "name": "Myers-Brown"
        }
      ],
      "name": "John Anderson",
      "role": "RightsHolder",
      "type": "Personal"
    }
  ],
  "creators": [
    {
      "affiliations": [
        {
          "identifiers": {
            "ror": "03yrm5c26"
          },
          "name": "Baker-Berg"
        }
      ],
      "identifiers": {
        "Orcid": "0000-0002-1825-0097"
      },
      "name": "Claudia Harrison",
      "type": "Personal"
    }
  ],
  "dates": [
    {
      "description": "Random test date",
      "start": "1998-02-16",
      "type": "Other"
    }
  ],
  "descriptions": [
    {
      "description": "Show risk dream total who trouble west. Fast probably tax including clear accept. Watch father whether ball. [...]",
      "lang": "eng",
      "type": "Abstract"
    }
  ],
  "embargo_date": "2003-04-04",
  "extensions": {
    "doi:osti_doi": "10.80447/1488048"
  },
  "identifiers": {
    "DOI": "10.9999/rdm.9999999",
    "arXiv": "9999.99999"
  },
  "language": "eng",
  "licenses": [
    {
      "identifier": "BSD-3",
      "license": "Berkeley Software Distribution 3",
      "scheme": "BSD-3",
      "uri": "https://opensource.org/licenses/BSD-3-Clause"
    }
  ],
  "locations": [
    {
      "description": "Random place on land for random coordinates...",
      "place": "Lutz",
      "point": {
        "lat": -66.90673,
        "lon": -70.626971
      }
    }
  ],
  "publication_date": "1975/1993-10-13",
  "recid": "tjqpc-02w64",
  "references": [
    {
      "identifier": "9999.99988",
      "reference_string": "Reference to something et al.",
      "scheme": "GRID"
    }
  ],
  "related_identifiers": [
    {
      "identifier": "10.9999/rdm.9999988",
      "relation_type": "Requires",
      "resource_type": {
        "subtype": "publication-book",
        "type": "publication"
      },
      "scheme": "DOI"
    }
  ],
  "resource_type": {
    "subtype": "publication-report",
    "type": "publication"
  },
  "subjects": [
    {
      "identifier": "subj-1",
      "scheme": "no-scheme",
      "subject": "Romans"
    }
  ],
  "titles": [
    {
      "lang": "eng",
      "title": "Fisher LLC's gallery",
      "type": "Other"
    }
  ],
  "version": "v0.0.1"
}
```

**Comment by cenouralm** [comment]
In order to replicate this issue I started by maing a new record draft using the API:
`curl -k -XPOST -H "Content-Type: application/json" https://127.0.0.1:5000/api/rdm-records -d '{
    "_access": {
        "metadata_restricted": false,
        "files_restricted": false
    },
    "_created_by": 1,
    "_owners": [1],
    "access_right": "open",
    "creators": [
        {
            "name": "Julio Cesar",
            "type": "Personal",
            "given_name": "Julio",
            "family_name": "Cesar",
            "identifiers": {
                "Orcid": "0000-0002-1825-0097"
            },
            "affiliations": [
                {
                    "name": "Entity One",
                    "identifiers": {
                        "ror": "03yrm5c26"
                    }
                }
            ]
        }
    ],
    "descriptions": [
        {
            "description": "A story on how Julio Cesar relates to Gladiator.",
            "type": "Abstract",
            "lang": "eng"
        }
    ],
    "identifiers": {
        "DOI": "10.9999/rdm.9999999",
        "arXiv": "9999.99999"
    },
    "licenses": [
        {
            "license": "Berkeley Software Distribution 3",
            "uri": "https://opensource.org/licenses/BSD-3-Clause",
            "identifier": "BSD-3",
            "scheme": "BSD-3"
        }
    ],
    "publication_date": "2020-08-31",
    "resource_type": {
        "type": "publication",
        "subtype": "publication-article"
    },
    "titles": [
        {
            "title": "A Romans story",
            "type": "Other",
            "lang": "eng"
        }
    ],
    "version": "v0.0.1"
}'`

After that I created a PUT request (where I have made a small change in the name):
`curl -k -XPUT -H "Content-Type: application/json" https://127.0.0.1:5000/api/rdm-records/5pv7s-jg742/draft -d '{
    "_access": {
        "metadata_restricted": false,
        "files_restricted": false
    },
    "_created_by": 1,
    "_owners": [1],
    "access_right": "open",
    "creators": [
        {
            "name": "Manuel",
            "type": "Personal",
            "given_name": "Julio",
            "family_name": "Cesar",
            "identifiers": {
                "Orcid": "0000-0002-1825-0097"
            },
            "affiliations": [
                {
                    "name": "Entity One",
                    "identifiers": {
                        "ror": "03yrm5c26"
                    }
                }
            ]
        }
    ],
    "descriptions": [
        {
            "description": "A story on how Julio Cesar relates to Gladiator.",
            "type": "Abstract",
            "lang": "eng"
        }
    ],
    "identifiers": {
        "DOI": "10.9999/rdm.9999999",
        "arXiv": "9999.99999"
    },
    "licenses": [
        {
            "license": "Berkeley Software Distribution 3",
            "uri": "https://opensource.org/licenses/BSD-3-Clause",
            "identifier": "BSD-3",
            "scheme": "BSD-3"
        }
    ],
    "publication_date": "2020-08-31",
    "resource_type": {
        "type": "publication",
        "subtype": "publication-article"
    },
    "titles": [
        {
            "title": "A Romans story",
            "type": "Other",
            "lang": "eng"
        }
    ],
    "version": "v0.0.1"
}'`

and the results were:
`TypeError: update() missing 3 required positional arguments: 'identity', 'id_', and 'data'`

**Comment by fenekku** [comment]
Thanks for replicating @cenouralm . Moving this to TODO and removing the good first issue tag.
