### ISSUE TITLE
Ensure links are generated

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#149]
It turns out to be much easier to start from a concrete case (BibliographicRecords) and generate links. Then abstract this away for other cases.  Nevertheless, we need to know what are the links we *do* want.

Here is what I think we need:

**When returning a single published record:**

- [x] self --- api link to record
- [x] self_html --- ui link to record
- [ ] files --- api link to files for the record     (this and the below 2 will depend on permissions) --> https://github.com/inveniosoftware/invenio-rdm-records/issues/151
- [x] edit --- api link to edit the record
- [x] delete --- api link to delete the record

**When returning a single draft record:**

- [x] self --- api link to draft
- [x] self_html --- ui url to deposit page
- [ ] files --- api link to files for the draft      (this and the below will depend on permissions) -> https://github.com/inveniosoftware/invenio-rdm-records/issues/151
- [x] publish --- api linkto publish the draft

**When returning a list of published records**

- [x] self --- api link to results with search parameters
- [x] next --- api link to next set of results with search parameters (next is only present if there is a next page of results)
- [x] prev --- api link to prev set of results with search parameters (prev is only present if there is a prev page of results)

**Are there links missing here?** @lnielsen

**Comment by fenekku** [comment]
new_version_html --- deposit page for new page of record

**Comment by lnielsen** [comment]
Also in the future:

- ``doi``
- ``thumbnail250``
- ``thumbnail1000``

**Comment by ppanero** [comment]
- versions_html --- link to the latest html version or (this changes from current zenodo implementation) a landing page with a list of versions (I would vote for this second approach).
- latest_html --- link to the latest html version, would be the same as `self_html` if it is the latest version of the record.
