### ISSUE TITLE
cli: demo records don't get properly indexed

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#157]
Records (and their drafts) created via the demo CLI, go through the `BibliographicRecordService`, which eventually sends the records to be indexed under the `records` index name. This basically prevents the `before_record_index` signal receivers from running, since they're usually subscribed on the index name `records-record-v1.0.0`. In the end keys like `_communities` and metadata extensions end up not being indexed and cause issues during REST API serialization.

For this to be solved either:

- the `before_record_index` has to change to become flexible and allow e.g. indexes to be checked via wildcards (i.e. `records*`)
- index naming has to be normalized across modules (i.e. always use the alias `records`)

**Comment by ppanero** [comment]
@lnielsen can confirm, but the idea was to get rid of those signlas in the new backend, and provide a configurable list of actions to perform before/after index. Using some sort of command pattern.

**Comment by lnielsen** [comment]
This is blocking the August release, as nobody can load the demo record so we need as a minimum a temporary solution.

**Comment by slint** [comment]
Quick solution would be to add the full index names (i.e. `records-record-v1.0.0` and `drafts-draft-v1.0.0`) in the `record_to_index` function in https://github.com/inveniosoftware/invenio-drafts-resources/blob/3050402a80d02144af5cfcd5f259eca229820599/invenio_drafts_resources/services/search.py#L26-L28

**Comment by fenekku** [comment]
August release update: invenio-cli demo works without any of these changes (at least I didn't implement them...) in so far as there is no connection between communites and records by default.

Part of @lnielsen and @slint effort is to settle on a long-term solution for this is my understanding.

**Comment by ppanero** [comment]
Closing this since the workflow changed and other modules will need to be integrated (i.e. get out of the old records-rest way)
