### ISSUE TITLE
jsonschema: removed fields

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#16]
The following fields have been removed in order to use DataCite's schema according to what was decided https://github.com/inveniosoftware/invenio-rdm-records/issues/18.
- **contributors**:
    - ids

**Comment by fenekku** [comment]
I don't have access to the linked document. Even through my institution login, I am getting `Internal server error`

**Comment by ppanero** [comment]
Closing this since issues on problematic fields will be treated in their own issue/rfc/pr
