### ISSUE TITLE
Parent PID configuration for non-DataCite setup

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-rdm-records#1652]
Package version (if known): v12d

## Describe the bug
The current configuration of parent PIDS assumes that DataCite is enabled https://github.com/inveniosoftware/invenio-rdm-records/blob/a9eab71bf8b55efc90d2ab9268bbc45a4e2eab55/invenio_rdm_records/config.py#L377, but the default is that DataCite is not enabled https://github.com/inveniosoftware/invenio-rdm-records/blob/a9eab71bf8b55efc90d2ab9268bbc45a4e2eab55/invenio_rdm_records/config.py#L394. This will result in issues for a standard install.

- Should DataCite be a requirement?
- Do we need a config to turn off parent pids? (This would be useful for us)
- Can a different pid be used as the default?

**Comment by utnapischtim** [comment]
Note: the parent_doi is used in [invenio_rdm_records/service/config.py](https://github.com/inveniosoftware/invenio-rdm-records/blob/bbdd2251ad275274a6282f47c075c51893c2b035/invenio_rdm_records/services/config.py#L362) i think this should be a ConditionalLink as in [here](https://github.com/inveniosoftware/invenio-rdm-records/blob/bbdd2251ad275274a6282f47c075c51893c2b035/invenio_rdm_records/services/config.py#L324)

**Comment by utnapischtim** [comment]
related to discussion around DOI's of restricted records: https://github.com/inveniosoftware/product-rdm/issues/178

**Comment by utnapischtim** [comment]
related to https://github.com/inveniosoftware/product-rdm/issues/194
