### ISSUE TITLE
api: rework `access/users` endpoint

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-rdm-records#1671]
EPIC: https://github.com/CERNDocumentServer/cds-rdm/issues/109

1. rename existing `access/users` endpoint to `access/grants`
2. create new endpoint for `access/users`

**Comment by carlinmack** [comment]
Would be good to have a discussion to align on https://github.com/inveniosoftware/invenio-rdm-records/pull/1673#discussion_r1505954150
