### ISSUE TITLE
vocabularies: licenses: wrong encoding of accents

### ISSUE THREAD

**Issue by ptamarit** [inveniosoftware/invenio-rdm-records#1725]
There are wrongly encoded characters in the [file `licenses.csv` on lines 222, 223 and 224](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/licenses.csv?plain=1#L222-L224).
They appear wrongly formatted in the GitHub UI as well as when opening the CSV file in a code editor (the file is correctly detected to be UTF-8).

**Comment by ptamarit** [comment]
@SotosTsepe This seems to have been introduced in https://github.com/inveniosoftware/invenio-rdm-records/pull/1721.
Could you please have a look?

**Comment by SotosTsepe** [comment]
@ptamarit Thanks for reporting, I'll go ahead and fix that
