### ISSUE TITLE
Draft/record show up as duplicate in user dashboard "Uploads" after being accepting community review request

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#1730]
Package version: InvenioRDM v12

## Describe the bug

If a record is published to a community after review it will appear as a duplicate in the user dashboard "My uploads" list.

## Steps to Reproduce

1. Create a community and set the review policy to allow curators, owners etc. to publish directly without review.
2. Create a new upload and publish it to the community.
3. In the user dashboard under "My upload" the duplicated entry will appear.
4. Duplicate will vanish if the record/upload edit form is opened once more (even if all changes in the form are discarded).

## Expected behavior

If an upload is published only the published record item should appear in the list in the user dashboard.

## Screenshots (if applicable)

![image](https://github.com/inveniosoftware/invenio-rdm-records/assets/1814661/3a759445-7954-4d28-a8d8-76a4eba52736)

**Comment by SarahW91** [comment]
Relevant discussion on Discord starting from here: https://discord.com/channels/692989811736182844/704625518552547329/1227963801890979870
