### ISSUE TITLE
Implement Creators and Contributors equivalent metadata fields 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#19]
This issue tracks implementation of the "creators" / "contributors" metadata fields.

An accompanying RFC would be the place to define and document to others those fields (I think). 

**Priming content for RFC (should be moved to it)**:

*Schema discussion starting point*

```json
    "<creators/contributors>": {
      "description": "Contributors in order of importance.",
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "ids": {
            "description": "List of IDs related with the person.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "additionalProperties": false,
              "type": "object",
              "properties": {
                "source": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          },
          "name": {
            "description": "Full name of person or organisation. Personal name format: family, given.",
            "type": "string"
          },
          "affiliations": {
            "description": "Affiliation(s) for the purpose of this specific record.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          },
          "email": {
            "type": "string",
            "description": "Contact email for the purpose of this specific record.",
            "format": "email"
          },
          "role": {
            "description": "",
            "type": "string",
            "enum": [
              "ContactPerson",
              "Researcher",
              "Other"
            ]
          }
        },
        "required": [
          "name"
        ]
```

For unknown authors, use DataCite's `unknown`. 

See [w3C recommendations on names](https://www.w3.org/International/questions/qa-personal-names).

Organization as author is something we will eventually want. Perhaps they are an alternative with their own fields. The organization use case may also be an opportunity to solve the "too many authors" problem. Organization ids: [Research Organization Registry](https://www.ror.community/)

*Why this field, these properties and this implementation?*

- For citation purposes 
- For DOI minting
- To respect w3C standard
- To disambiguate authors
- To allow auto-complete from a source

**Comment by tmorrell** [comment]
This looks like a good combination of creators and contributors.  Some comments (let me know if they should go somewhere else).

- I would break ids (or identifiers if we want to go more formal) out as a definition. That way it can be used for both people and affiliations. I think we want to support affiliation identifiers out of the box.
- I'm not sure source and value are the best labels for identifiers. Source kind of implies provenance, which isn't necessarily the case. DataCite goes with identifier and identifierScheme, which seems clearer. They also have SchemeURI, which is kind of useful but can also be repetitive.
- The identifier and scheme (or whatever they are called) should be required in the id section
- Having one name field and not splitting it into givenName and familyName seems like a reasonable simplification, but is worth discussing
- DataCite has a nameType field with values organizational and personal if we want to include organizations as authors.

**Comment by fenekku** [comment]
We have dealt with creators and contributors this sprint. This can be closed.
