### ISSUE TITLE
Data model extension

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#2]
As a developer-hoster I want to be able to extend the core metadata schema with fields specific to my domain so that my metadata schema addresses my needs. 

These custom fields are limited to the following types: array, string, integer and date.

**Links of interest**
*Marshmallow schema*
- https://github.com/zenodo/zenodo/blob/d56a7d5005d9982ebcaa7d7ea0091376000f017f/zenodo/modules/records/serializers/schemas/common.py#L498

*jsonschema*
- https://github.com/zenodo/zenodo/blob/d56a7d5005d9982ebcaa7d7ea0091376000f017f/zenodo/modules/records/jsonschemas/records/record-v1.0.0.json#L611

*Inner filling for ES indexing* 
- https://github.com/zenodo/zenodo/blob/fecfe1c38415266c4dcefe09d6009a31b9bc3663/zenodo/modules/records/indexer.py#L84
- https://github.com/zenodo/zenodo/blob/fecfe1c38415266c4dcefe09d6009a31b9bc3663/zenodo/modules/records/utils.py#L161
- https://github.com/zenodo/zenodo/blob/fe72e36cc6d04102dfd6791ab1082c9b7af75d6d/tests/unit/records/test_records_utils.py#L69

An example of such extension would be added biomedical profile fields:

The "biomedical" profile will have the following extensions to the core metadata (see #1) 

| Field or equivalent              | Notes                                                                                  | Why                                                                   | Task | Implemented |
| ------------------------------- | -------------------------------------------------------------------------------------- | --------------------------------------------------------------------- | ---- | ----------- |
| ~~Language `language`~~ | Language of the content, optional. Just 1 for now. | filtering, legacy | | in main model as `language` |
| Presentation location `presentation_location` | Location where content was *presented*, optional. Applies to exhibits and presentations. Geolocation values or controlled vocabulary values or both? | filtering, legacy | | |
| ~~Content location `content_location`~~ | Location pertaining to the content itself. (e.g., `Uganda` for dataset of vaccinated population in Uganda). Optional. Geolocation values or controlled vocabulary values (Feed from MeSH) or both? We may or may not be able to stick this in `terms` | searching, filtering, legacy | | in main model as `location`|
| Number in sequence `number_in_sequence` | Indicates page or order of record in an ensemble. Integer, optional | sorting, in collection record ordering, synergy with `part` relation type |      |    |
| ~~Private Note `private_note`~~  | Free text, optional. Used internally for repo managers. SUPER_USER, librarian, owner, proxy can see it.                                                                         | Need to understand use case better? |      | in main model as `internal_notes`      |
| ~~Subject: Name (re-use `terms`)~~| Name of person/organization referred in content (e.g. book about someone). Optional. Fed from controlled vocabulary | legacy, searching, filtering  |   | in main model as `subjects`  |

Note that acknowledgements are not included for now.
"Abstract" and "content date" will be addressed by core metadata.

**Comment by lnielsen** [comment]
- Reference issues: zenodo/zenodo#1758, zenodo/zenodo#1766, zenodo/zenodo#1765
- Commits/PRs: zenodo/zenodo#1772, [commit](https://github.com/zenodo/zenodo/commit/6b5417ed00260544527c34a2dc3897f8dfcab785)
