### ISSUE TITLE
Fill description for "user" in jsonschema

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#217]
Should replace`".."` by an actual description in https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/jsonschemas/records/record-v1.0.0.json#L235 .

_Originally posted by @fenekku in https://github.com/inveniosoftware/invenio-rdm-records/pull/212#discussion_r508074720_

**Comment by fenekku** [comment]
No there isn't. The description for `"user"` is simply missing.

**Comment by lnielsen** [comment]
@fenekku Is this one still relevant?

**Comment by fenekku** [comment]
Nah, it was a minor comment for https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/jsonschemas/records/definitions-v1.0.0.json#L242 , but now this provides it https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/jsonschemas/records/definitions-v2.0.0.json#L444.

Closing.
