### ISSUE TITLE
moderate: change from 'Orcid' to 'orcid' 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#218]
moderate: that change from 'Orcid' to 'orcid' above will need to be spread here and everywhere in rdm-records

_Originally posted by @fenekku in https://github.com/inveniosoftware/invenio-rdm-records/pull/212#discussion_r508081208_

**Comment by ppanero** [comment]
This has been solved by https://github.com/inveniosoftware/invenio-rdm-records/pull/220

The idea behind it is that every vocabulary item will have a lowercased id, then the labels can be camel case or whatever else. This will be less error-prone when comparing etc.
