### ISSUE TITLE
support name inference on contributors/creators

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#224]
## Is your feature request related to a problem? Please describe.
This feature is needed to properly support naming (and potentially helped deduplication) on the RDM data model.

## Describe the solution you'd like
The creators schema (which is inherited by contributors, therefore it applies to it too) has three attributes:

```python
name = SanitizedUnicode(required=True)
type = SanitizedUnicode(required=True, validate=validate.OneOf(
                choices=NAMES,
                error=_(f'Invalid value. Choose one of {NAMES}.')
            ))
given_name = SanitizedUnicode()
family_name = SanitizedUnicode()
```

`type` can be *organizational* or *personal*. 
- If `type == orgnizational` the required field is `name`.
- if `type == personal` the required fields are `given_name` and `family_name`, and `name` should be filled in with the *family_name, given_name* format (e.g. `Panero, Pablo`).

The successful solution would provide:
- [x] logic to infer names (e.g. `name` for the second case)
- [x] validation for the corresponding cases
- [x] tests

## Additional context

See `invenio_rdm_records/services/schemas/metadata.py` specially `ContributorsSchema` and `CreatorsSchema`.

**Comment by fenekku** [comment]
I am going to go with filling the first / last name from the name if "type == personal". That work?

**Comment by zzacharo** [comment]
Closed via https://github.com/inveniosoftware/invenio-rdm-records/pull/291
