### ISSUE TITLE
landing page: publication date should be localized

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#242]
## Describe the bug

The publication date is not localized on the publication date.

## Steps to Reproduce

1. Go to the landing page of any record (https://127.0.0.1:5000/records/<recid>)

## Expected behavior

The text should read like in the expected screenshot below. Note, do not add the version or make a label around the date. It's only the actual text which is wrong. The styling is fine.

## Screenshots (if applicable)

Current:

<img width="436" alt="Screenshot 2020-11-02 at 14 53 28" src="https://user-images.githubusercontent.com/1698163/97875863-4a220c80-1d1b-11eb-988d-9a47e6d895ee.png">

Expected:

<img width="267" alt="Screenshot 2020-11-02 at 14 55 20" src="https://user-images.githubusercontent.com/1698163/97875956-6f167f80-1d1b-11eb-9c85-687caa7a2b3b.png">

**Comment by lnielsen** [comment]
For the implementation, please create a template filter ``format_edtf`` that takes care of formatting an EDTF date.

**Comment by ppanero** [comment]
Once moved to a different package it can be used by:
- https://github.com/inveniosoftware/invenio-rdm-records/issues/203 (search results) solved in https://github.com/inveniosoftware/marshmallow-utils/pull/18/files and made use of in https://github.com/inveniosoftware/invenio-rdm-records/pull/211/files

**Comment by ppanero** [comment]
Waiting for https://github.com/inveniosoftware/invenio-rdm-records/pull/240 and https://github.com/inveniosoftware/invenio-app-rdm/pull/362 to get merge to make things consistent

**Comment by lnielsen** [comment]
Currently, it's localized, but not in the long format.

**Comment by ppanero** [comment]
Related to https://github.com/inveniosoftware/invenio-rdm-records/issues/248
