### ISSUE TITLE
landing page: entity may not have 'affiliations'

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#256]
Package version (if known): 0.23.2

## Describe the bug
When filling out a record with a creator without affiliation and publishing, one is redirected to the landing page that crashes with
`jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'affiliations'` for `<div> {{entity.affiliations[0].name}}</div><br />` because an entity (creator or contributor) may not have affiliations (even if empty array, the indexing followed by attribute access would cause an error).

## Steps to Reproduce
1. Go to '/uploads/new'
2. Fill out a record without affiliations for creator
3. Save and Publish
4. See error described above

## Expected behavior

It should be fine to not pass any affiliations. There should be a check to make sure there are affiliations when accessing affiliations.

## Additional context
Even for showing only hover affiliations this applies.

**Comment by ppanero** [comment]
I was unable to reproduce this error, however a related one (in the footnotes) triggered when no affiliations. See more info at: https://github.com/inveniosoftware/invenio-rdm-records/pull/258
