### ISSUE TITLE
Revisit Funding Field

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#264]
We have introduced a placeholder for `FundingSchema`. The concrete use cases and scenarios should be discussed and established so that appropriate functionality is implemented.

- Should an award include its funder in its own schema.
- Just a funder could be supported
...

**Comment by lnielsen** [comment]
Zenodo team is working on the funding field in this iteration, and have specific issues in invenio-vocabularies so closing this one.
