### ISSUE TITLE
ux: contributors' affiliations are not shown

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#271]
Package version (if known): 0.23.4

## Describe the bug
Despite filling a contributor's affiliations, they don't show up in the record landing page.

## Expected behavior
Contributors' affiliations should be displayed like they are for creators.

## Screenshots (if applicable)

![record_landing_page_contributors](https://user-images.githubusercontent.com/1932651/98726137-ba541200-235b-11eb-8d0b-14d9e6c797a8.png)

**Comment by lnielsen** [comment]
![Screenshot_2020-11-09_at_16 38 35](https://user-images.githubusercontent.com/1698163/98801566-43c61b80-2412-11eb-917c-d3d1070647df.png)
