### ISSUE TITLE
ux: empty description is wrongly displayed on landing page

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#274]
Package version (if known): 0.23.5

## Describe the bug

When no description is filled in, some raw JSON is displayed in the description field (see screenshot)

## Steps to Reproduce

1. Create/edit a draft without a description and publish
2. Go to the published record's landing page

## Expected behavior

Primary description should either be a required field, or if not present it shouldn't be displayed at all

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1814661/98800688-06ad5980-2411-11eb-83cf-bd8f0378065d.png)

**Comment by fenekku** [comment]
Fixed a while ago. Empty descriptions are not shown.
