### ISSUE TITLE
files [dumper]: ES dump/load

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#287]
Files fields require special dumping/loading regarding how they are indexed in ES:

- [ ] Instead of a dictionary-like structure, `files.entries` should be indexed as a list of objects, so that it is possible to query for e.g. `filename:"article.pdf" 
- [ ] When loading from ES, bucket and files information has to be parsed to make them accessible via `record.files` and `record.bucket`

**Comment by lnielsen** [comment]
I've linked the issue into the product board, and I'm closing this issue here, as I don't see we will fix this anytime soon.
