### ISSUE TITLE
ux: deposit form uses the term "Keywords" and record page uses "Subjects" - align

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#289]
Package version (if known): october

Align to use "keywords" or "subjects" in both.

(Librarians at our site are keen on user entered values becoming keywords and controlled vocabulary keywords becoming subject terms... but that's probably too fancy for now)

**Comment by ppanero** [comment]
I think it should be "subjects" everywhere, taking into account that's what datacite has (and we put in the data model).

**Comment by fenekku** [comment]
"Subjects" it is.

**Comment by fenekku** [comment]
This was actually solved some time ago. Closing.
