### ISSUE TITLE
Mint records with DataCite-like provider

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#29]
Confirmation is needed on this task:

Implement and integrate minters to generate internal record persistent identifiers (`pid_type=recid`). Rather than legacy record identifiers, random 10-character alphanumeric string (with checksum) should be used.

- [x] implement provider, minter and fetcher in invenio-pidstore: https://github.com/inveniosoftware/invenio-pidstore/pull/125
- [x] integrate in invenio-rdm-records fake records: https://github.com/inveniosoftware/invenio-rdm-records/pull/31 

This is the task that will finally connect base32-lib functionality with record minting (via invenio-pidstore).

**Comment by fenekku** [comment]
Did it in invenio-pidstore mostly.

**Comment by ppanero** [comment]
@fenekku Shall we link each point's PR (So we only have issues in the board?) I beleive the first item is https://github.com/inveniosoftware/invenio-pidstore/pull/125, no?

**Comment by fenekku** [comment]
Yes, done.
