### ISSUE TITLE
ux: landing page: hand pointer + show affiliations registers clicks outside of the button

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#304]
Package version (if known): november release / 0.24.5

## Describe the bug
The mouse pointer turns to hand in the creator section.

When there are affiliations, clicking anywhere on the html line with Show affiliations button registers as a show affiliation click.  

![hand_pointer](https://user-images.githubusercontent.com/1932651/126801712-92fc4f9e-5de2-4828-a87f-f4f09985bdd0.png)

## Expected behavior
- Regular mouse pointer in that area
- Only by clicking on the show affiliations button should the affiliations be shown.

**Comment by fenekku** [comment]
Still applicable, unmarking it as stale.

**Comment by fenekku** [comment]
still valid.

**Comment by lnielsen** [comment]
I'm not able to reproduce. @fenekku Can you provide more details....

**Comment by fenekku** [comment]
Here is a video:

![affiliations](https://user-images.githubusercontent.com/1932651/126985470-8bf908b7-6656-409f-84b5-1a3db15f4151.gif)

(note that I don't click on the button at the end)

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-app-rdm/pull/1072
