### ISSUE TITLE
Tests hanging for minimal requirements

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/invenio-rdm-records#314]
Package version (if known): 0.25.5

## Describe the bug
Tests for the minimal requirements are looping when new pip resolver is trying to solve dependencies. The resolver starts looping over dependencies, causing tests to take very long time to complete. (>6h)

## Steps to Reproduce
1. Run GH actions on any PR/branch
2. See the problem for the job on the minimal requirements.

## Expected behavior
possible solution is to 
a) fix dependencies (not trivial)
b) use the old pip resolver (by specifying the parameter for the pip command) for the minimal requirements job, until the new one gets fixed

**Comment by fenekku** [comment]
Looks like this was fixed.
