### ISSUE TITLE
Create affiliations vocabulary

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#328]
YOu might need to fix this one first:https://github.com/inveniosoftware/invenio-vocabularies/issues/48

Task is first to add the affiliation vocabulary to Invenio-Vocabularies and have ``/api/affiliations`` working in InvenioRDM. Another task will be created to do the relationship.

Data should come from https://doi.org/10.6084/m9.figshare.c.4596503.v7
Parser in: https://gist.github.com/ppanero/ef9848e848de16bdb280ef5209f4c6fa

Initial data model:

```python
{
   "id": "https://ror.org/01k4yrm29",
   "pid": {...},
   "name": "Korea Institute of Science & Technology Information",
   "titles": {
      "en": "Korea Institute of Science & Technology Information"
      "ko": "한국과학기술정보연구원"
   },
   "acronym": "KISTI",
   "identifiers": [
      {"scheme": "isni", "identifier": "..."},
      {"scheme": "ror", "identifier": "...repeated from id..."},
      {"scheme": "fundref", "identifier": "..."},
   ]
}
```

**Data layer**

- [x] Create a packge in ``invenio_vocabularies/contrib/<name plural>``.
- [x] JSONSchema: ``jsonschemas/<name plural>/<name>-v1.0.0.json``
    - Use defs ``title``, ``description``, ``icon`` from ``invenio_vocabularies/records/jsonschemas/vocabularies/definitions-v1.0.0.json`` (preferably) 
    - Use defs ``id``, ``schema``, ``pid`` from invenio-records-resources.
- [x] Mappings: Add mappings for v6 and v7 following (``mappings/{v6,v7}/<name plural>/<name>-v1.0.0.json``)
- [x] Record type factory: ``<name-plural>.py``:
    - Permissions policy use ``invenio_vocabularies/serivces/permissions.py:PermissionPolicy``
    - Endpoint ``/<name-plural>``
- [x] API/Models: ``api.py`` and ``models.py`` (use from factory)
- [x] Alembic recipe for creating tables (``invenio_vocabularies/alembic``).

**Service layer**

- [x] Service schema: ``schema.py``
    - [x] Inherit from ``BaseVocabularySchema``.
    - [x] Match up with JSONSchema
- [x] Service: ``service.py``
    - [x] Add SearchOptions:
        - [x] Need to check if we inherit from ``VocabularySearchOptions``.
        - [x] suggest_parser_cls may need tweaking
        - [x] Need facets?
        - [x] Need facets labelling? (i.e. will RDM-Records have facets over this vocab)
    - [x] Customize components? Probably need ``DataComponent``, ``PIDComponent``. 
    - [x] Do we use PIDs or UUIDs.

**Resource layer**

- [x] Config:
    - [x] May need to define serializer ``"application/vnd.inveniordm.v1+json"`` with associated schema.

**Tests**

- [x] Schema  must be validated with good and bad data.
    - [x] Data layer
    - [x] Service layer
- [x] REST API
    - [x] Serializations ``json`` and ``inveniordm v1``.
    - [x] Actions: Search, create, read, update, delete.

Complete all above first. Then:

- [x] Invenio-RDM-Records: 
    - [x] Ext.py: register service and resource.
    - [x] setup.py: entry points

**Comment by ppanero** [comment]
> Do we use PIDs or UUIDs.
Discussed IRL -> UUIDs

**Comment by ppanero** [comment]
Discussed IRL

> - No UI serializer
correct
> - No need to customize the response handlers
Correct
> - Tweaking the search parser to boost name and acronym instead
correct
> - Labelling --> This part makes me doubt... Which is what we discussed but... idk (e.g. CERN  fr-en)
UI widgets will display just name, but when you search for a french name you'll be able to get a search hit on it
