### ISSUE TITLE
Migrate existing vocabularies

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#329]
Migrate the existing vocabualries staring with:

- [x] Resource type
- [ ] Roles (creators/contributors)
- [ ] Title types

Replaces inveniosoftware/invenio-app-rdm#187 (Please go read this issue)

**Comment by fenekku** [comment]
Replaced by https://github.com/inveniosoftware/invenio-app-rdm/issues/926
