### ISSUE TITLE
Implement RFC JSONSchema resolution and registry

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-rdm-records#356]
Implement the changes proposed in the [RFC - JSONSchema resolution and registry](https://github.com/inveniosoftware/rfcs/blob/master/rfcs/framework-0042-jsonschema-validation.md).

- Invenio-Records:
  - [x] Allow overwriting the RefResolver and inject the store.
  - [x] Build the ``InvenioRefResolver``
  - [x] Add tests (specifically show that nested schema's work).
- Invenio-JSONSchemas:
  - [x] Add support for exporting the registry with ``local://`` schema.
  - [x] Add validation of if ``$id`` matches the registry key.

- Invenio-RDM-Records:
  - [x] Make use of the new resolver and store in InvenioRDM. 
  - [x] Refactor the existing JSONSchemas so that e.g. definitions can live in their own schema.

**Comment by origliante** [comment]
I'm temporarily solving it by adding the following to the image Dockerfile:
```
COPY ./records_api.py /usr/local/lib/python3.8/site-packages/invenio_rdm_records/records/api.py
COPY ./vocabularies_api.py /usr/local/lib/python3.8/site-packages/invenio_vocabularies/records/api.py
```

And having, for example in records_api.py, something like the following:
```
import os
site_hostname = os.environ.get('INVENIO_SITE_HOSTNAME', 'localhost')
```
And:
```
    schema = ConstantField(
       '$schema', f'https://{site_hostname}/schemas/records/record-v1.0.0.json')
```

**Comment by lnielsen** [comment]
RFC for changes to Invenio-Records and Invenio-JSONSchemas that would solve this issue: https://codimd.web.cern.ch/x9wZmPRsQoO8SrZkl57PlQ
