### ISSUE TITLE
Combine / disambiguate _access and access_right 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#37]
2 parts to this task: discuss the differences / combination and implement.

`access_right` can currently be: 

- `'open'`
- `'embargoed'`
- `'restricted'`
- `'closed'`

`'_access'` can be:

```
    'metadata_restricted': <true|false>    
    'files_restricted': <true|false>
```

This leads to strange combinations: an open access record with files restricted or a record with metadata restricted but files not restricted or an open record with metadata restricted... The first in particular is something participants in our usability sessions have complained about: "An open access record should have its files available" to paraphrase.

What also makes things hard to keep straight is that we have a `rights` field (the license) and an `access_levels` field.

Because of this, I suggest we merge them together. This way, only combinations that make sense are possible and the combinations are not across different fields but within 1 field. We can always have the UI reflect what we want from this 1 field. Enforcing a strict semantic we can cover most cases (I think?) with something like the following for example:

| New "access_right" field | metadata available?              | files available? |
|----------------------------------|----------------------|-----------------------------------|
| `open`     | :heavy_check_mark: | :heavy_check_mark: |
| `embargoed`   | :heavy_check_mark: | :x: until embargo date (unless user has permissions) | 
| `scheduled` (or `embargoed` with added metadata)  | :x: until embargo date (unless user has permissions) | :x: until embargo date (unless user has permissions) | 
| `restricted`   | :heavy_check_mark: | :x: (unless user has permissions) | 
| ~~closed~~ `private`     | :x: (unless user has permissions) | :x: (unless user has permissions) |

I am completely fine with having `access_right` be bibliographic AND "interpreted" metadata.

What are your thoughts @lnielsen @ppanero ?

[**UPDATED** 2019-12-20]

**Comment by lnielsen** [comment]
Separate issues have been opened for the access implementation
