### ISSUE TITLE
datamodel: treating internal fields with `_`

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#38]
Currently the internal fields are prefix with underscore. However, the user submits the record without them (e.g. `access`).

An issue also arises when displaying the record. Currently the record view shows the record with `_access`.

- Marshmallow?
- Record API class?

**Comment by ppanero** [comment]
@fenekku during some chat for on other topics, this matter arised. One point on favour of using `_` is to "tell" harvesters which fields they should ignore because they are used for the internal operations / working functionality of the repository.

(I know we agreed to do it anyway, but is nice to know more points in favour of it :) )

**Comment by fenekku** [comment]
Ok. I will add this to the agenda for tomorrow perhaps.

**Comment by fenekku** [comment]
Metadata and details will be discussed at January meeting.
