### ISSUE TITLE
Access level metadata

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#47]
Implement access levels metadata per record.

**Comment by fenekku** [comment]
RFC: https://github.com/inveniosoftware/rfcs/pull/13/files

Initial implementation: https://github.com/inveniosoftware/invenio-records-permissions/pull/29/files  (to revisit since a while ago...)

**Comment by lnielsen** [comment]
Separate issues are opened with a detailed design.
