### ISSUE TITLE
Unpublished drafts: some of the rendered links aren't valid

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-rdm-records#470]
Package version (if known): 0.28.10

## Describe the bug
Some of the links rendered in (unpublished) drafts aren't valid (they result in a 404).

## Steps to Reproduce
1. Create and save (but do not publish) a draft
2. `curl` the draft
3. Follow the `latest` or `latest_html` link
4. See that it results in a 404

## Expected behavior

The links should not be generated in the first place.

## Additional context

The `marshmallow-utils.fields.links.Link` class offers a possibility to do conditional rendering: https://github.com/inveniosoftware/marshmallow-utils/blob/master/marshmallow_utils/fields/links.py#L52
This should probably be used.

**Note**: This is very similar to, but not entirely the same as #468, which deals with wrong lookups of entities.
This issue concerns actually non-existing targets.

**Comment by lnielsen** [comment]
Should have been fixed in the latest master branches.

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-rdm-records/pull/800
