### ISSUE TITLE
Local test 'unbound variable' issue

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-rdm-records#493]
Package version: 0.29.3

## Describe the bug
I get a 'unbound variable' error when trying to run tests locally

## Steps to Reproduce
1. Install InvenioRDM
2. Clone invenio-rdm-records into inveniordm directory
3. Install with `pipenv run pip install -e '.[all]'`
4. `pipenv run ./run-tests.sh`
5.  See error: ./run-tests.sh: line 57: pytest_args[@]: unbound variable

## Additional context

I'm running locally on a mac with zsh as the default shell. There is no difference if I use 'pipenv run bash run-tests.sh'.

**Comment by ppanero** [comment]
Is this still the case? Was it the old version of bash?

**Comment by tmorrell** [comment]
Old version of bash issue
