### ISSUE TITLE
serializers: datacite serialization of resource types and other vocabularies

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#529]
In the datacite serializer, there are several values that have to pass by some transformations that would make them suitable to be vocabularies.

- [x] ResourceType: It is already a vocabulary, but uses the old implementation and there is no easy way of obtaining the `datacite` values.
    - [ ] Zenodo does some overwritting of datacite subtypes by openaire ones. Should the RDM schema/serializer do the same?
    - [x] Edit the test to make sure to enable the resource type checking (currently serializing and getting a `FIXME
- [ ] There are many *types* (e.g `nameType`, `contributorType`, `identifierType`) that have to be capitalized or uppercased, and similar. For the test case this works fine (and passes using `capitalize()`. However, what happens when some case of capitalization in the middle of the type comes up (i.e. `ThisIsAnExample`). Could be made into vocabularies.
    - [ ] Search for appearances of `capitalize` in fields.methods and post_dumps 
    - [ ] Search for appearances of `upper` in fields.methods and post_dumps

**Comment by fenekku** [comment]
For point 1 about the old vocabulary approach for resource_type: the quick approach should be:

```python

resource_type_vocab = Vocabularies.get_vocabulary('resource_type')
# entry_key is a dict with 'type' and/or 'subtype' keys or a specifically formed string. See `invenio_rdm_records/vocabularies/resource_type.py`. 
entry = resource_type_vocab.get_entry_by_dict(entry_key)
# datacite compatible values can then be retrieved:
entry["datacite_general"] 
entry["datacite_type"]
```

**Comment by ppanero** [comment]
The datacite part has been migrated properly, see [here](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/resources/serializers/datacite/schema.py#L193). If the unanswered questions of the description are not needed, this can be closed.

**Comment by fenekku** [comment]
I think we can do for the `type`s what we did for the `resource_type` (use conversion found in props). So in the end those will be addressed when dealing with those types. Let's close this.
