### ISSUE TITLE
marshmallow: evaluate fields.Str vs SanitizedUnicode

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#53]
Several fields, such as `type`, are strings that can only take as value one of an enumeration. Therefore at the moment there is no need for them to be sanitized and could go along with just being a `Str()`. However, if we open these to customization (e.g. introduce your own CVs) it might cause problems (maybe in other languages that are not English).

Run some tests on performance from `marshmallow.fields.Str` vs `invenio_records_rest.schemas.fields.SanitizedUnicode`.

1 load/dump:

``` console
Sanitized: 0.0006556510925292969 seconds
Marshmallow Str: 0.0002028942108154297 seconds
```

1000 load/dumps:

``` console
Sanitized:  0.18001985549926758 seconds
Marshmallow Str: 0.09990668296813965 seconds
```

100000 load/dumps:

``` console
Sanitized: 18.859431743621826 seconds
Marshmallow Str: 10.20322585105896 seconds
```

**Comment by fenekku** [comment]
**Grooming**
This should be tackled when we deal with #5

**Comment by fenekku** [comment]
I think this can be closed. The bottom line: 
- if we know the string will never be used to hold potential internationalized string, then use Str  (e.g. enums)
- otherwise use SanitizedUnicode (e.g. free text, translated text)
