### ISSUE TITLE
resources: move invenio_rdm_records.serializers to invenio_rdm_records.resources.serializers 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#533]
Move ``invenio_rdm_records.serializers`` to ``invenio_rdm_records.resources.serializers ``

**Comment by ppanero** [comment]
I did this as part of last sprint: https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/resources/serializers 

However, it is not the case in `invenio-records-resources` ... See [here](https://github.com/inveniosoftware/invenio-records-resources/tree/master/invenio_records_resources)

**Comment by lnielsen** [comment]
The XMLSerializer should eventually be removed as it's not usable in the form it is now.
