### ISSUE TITLE
serializers: datacite serialization of publication year

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#539]
The RDM datamodel contains a `publication_date` which is handled by a `marshmallow_utils.EDTFDateString` field. This can also handle ranges... Datacite serialziation requires a `publicationYear`. 

- [x] How to obtain the year from the given string
- [x] Can the `EDTFDateString` be reused and some how made accessible the `year`?

**Comment by tmorrell** [comment]
`publicationYear` is not a well-loved field in DataCite, since the actual data fields are much more descriptive. It's used for citation purposes, but DataCite will prioritize the date field if they are present. I would keep things simple and just strip out the year, or the first year in a range.

**Comment by ppanero** [comment]
So it will always favor the `Issued` date... Can actually "publication dates" have ranges?

**Comment by tmorrell** [comment]
It's a real uncommon edge case. The only scenario I can imagine is if you're putting a whole bunch of journal articles into a single record. 

I've done some testing, and with the Rest API DataCite actually accepts a range for `publicationYear` but only saves the first year. I think we should follow this implementation and only send the first year. It could be as simple as just returning the first 4 numbers in the EDTFD date.

**Comment by lnielsen** [comment]
Agree with Tom, simply usage first possible year of publication
