### ISSUE TITLE
[Parent Issue] datamodel: still todo

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#54]
TODO as outcome of https://github.com/inveniosoftware/invenio-rdm-records/pull/49:

- Implement versioning (`conceptrecid` minting)
- OAI serializing/schema, add to tests and fixtures.
- Customization of enums
- *Resource types* are loaded from a JSON file. We need to converge on how to load them, for all enums.
- `IdentifierScheme` could be reused in many other schemas. However, there is no easy and clean way to flatten its attributes. Tested `Pluck` and `Method`. The latter worked but it has a more difficult code comprehension, which in my perspective makes is not a good choice.
- Tests for `access_condition` since the access part is not fully defined yet. It is not added to the fixtures either.
- Tests for `FilesSchema`, since is `dump_only` (see Zenodo). How should this be tested?
- Access: https://github.com/inveniosoftware/invenio-rdm-records/issues/37

**Comment by fenekku** [comment]
Breaking this up into smaller issues and closing:

- Implement versioning (conceptrecid minting) -> #59 
- OAI serializing/schema, add to tests and fixtures. -> #64
- Customization of enums e.g. resource types -> #5 
- IdentifierScheme -> #65
- access_condition -> #66
- Serialization of FileSchema -> #67
