### ISSUE TITLE
resources: create PID redirecting endpoint

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#540]
Create an endpoint that can redirect locally managed PIDs redirection, like `https://127.0.0.1:5000/doi/<doi>`. Should it even be `https://127.0.0.1:5000/<pid_type>/<pid_value>` to allow other non-DOI pids?

**Comment by ntarocco** [comment]
Implemented here: https://github.com/inveniosoftware/invenio-app-rdm/pull/801
