### ISSUE TITLE
serializers: strategy to choose one from multiple affiliation identifers

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#543]
InvenioRDM datamodel accepts multiple identifiers for the affiliation schema of a contributor/creator, meaning it is a list. However, datacite accepts only one. How do we serialize when there are multiple?

- Choose the first?
- Favour ROR since DataCite does something with it?

**Comment by lnielsen** [comment]
Leaving as is, means people can choose if it's really important to them, so I'll close this one for now.
