### ISSUE TITLE
resources: add draft endpoints for iiif manifest and iiif viewer

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#613]
Currently we have IIIF endpoints for the manifest and the viewer. However, they only work for records (published) we need them too for drafts?

We have:

- `/api/iiif/v2/<pid_value>:<filename>/full/750,/0/default.jpg`
- `/api/records/<pid_value>/iiif/manifest`

Might need:

- `/api/iiif/v2/draft/<pid_value>:<filename>/full/750,/0/default.jpg`
- `/api/records/<pid_value>/draft/iiif/manifest`

**Comment by lnielsen** [comment]
The endpoints i think is controlled according to the API spec, so I think you have to include it in the key (e.g. ``preview:<pid_value>:<filename>``)

**Comment by lnielsen** [comment]
Tracked in #615
