### ISSUE TITLE
Language in Json-Schema not correctly referenced

### ISSUE THREAD

**Issue by wgresshoff** [inveniosoftware/invenio-rdm-records#620]
Package version (if known): 3.0

## Describe the bug
The language definition in https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/jsonschemas/records/record-v3.0.0.json is not correctly referenced. In lines 68 and 219 instead of 

```
"lang": {"ref": "local://records/definitions-v1.1.0.json#/language"}
```

should be
```
"lang": {"$ref": "local://records/definitions-v1.1.0.json#/language"}
```

**Comment by fenekku** [comment]
Closed via: https://github.com/inveniosoftware/invenio-rdm-records/pull/621
