### ISSUE TITLE
Languages in Datacite are defined by RFC3066 but the internal representation is exported

### ISSUE THREAD

**Issue by wgresshoff** [inveniosoftware/invenio-rdm-records#629]
Package version (if known): 4.0

## Describe the bug
The datacite serializer serializes the languages as they are. While in datacite schema a language is defined by RFC3066, basically a 2-letter code plus optionally - and the country code. Might there be a problem with minting a DOI?!

## Steps to Reproduce
1. Not really reproducible?!

## Expected behavior
Languages should be exported according to RFC3066.

**Comment by ppanero** [comment]
@fenekku WDYT about approaching this in a similar fashion than resource_types (i.e. use props to have a `datacite_type` sort of)... Alternatively, we can use `pycountry` (but this is what we are using to migrate them - see `vocabularies/languages.py`). I'm thinking we can kill all at once migrating and that's it then just use form props.

**Comment by fenekku** [comment]
Agreed. Keeping the 2-letter code in the `props` will allow us to fetch it directly when serializing for datacite.

**Comment by ppanero** [comment]
context: the mentioned RFC allows both ISO 639-1 (2 letters) and ISO 639-2 (3 letters). However, DataCite explicitly mentions only ISO 639-1
