### ISSUE TITLE
Implement OAI-PMH serialization

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#64]

**Comment by fenekku** [comment]
Probably a good contender for external partners to implement.

**Comment by wgresshoff** [comment]
@fenekku Can I help here somehow? I need a hint about where/how to start. The documentation of invenio-oai isnot very helpful.

**Comment by lnielsen** [comment]
@wgresshoff Most of this stuff is done  - see the in review column in https://github.com/orgs/inveniosoftware/projects/77 - We missing green light on the CI build for Invenio-OAIServer and hope to look at it today or mon/tue next week. After that it would be great if you could help test it. Especially the Dublin Core export format as well as running a OAI-PMH validator on it woudl be helpful.

**Comment by wgresshoff** [comment]
@lnielsen I can do that. But there are surely some metadata formats I can implement serializers for. Have a look here https://repositorium.uni-muenster.de/oai/miami?verb=ListMetadataFormats what our repository currently supports. epicur and xMetaDissPlus for us are "must have" as the german national library relies on them.
