### ISSUE TITLE
Add missing fields in the JSON CSL Serializer.

### ISSUE THREAD

**Issue by Pineirin** [inveniosoftware/invenio-rdm-records#649]
It may be possible to add some extra fields present in zenodo, such as:
- container_title
- page 
- volume 
- issue 
- publisher_place
- event
- event_place
It may be needed to review the generation of the field, note, as discussed in the pull request cited below, the date should also be reviewed.
This possibility was proposed in: https://github.com/inveniosoftware/invenio-rdm-records/pull/644

**Comment by ppanero** [comment]
@Pineirin this issue should reflect the discussion/questions about the `note` field, could you add them?

**Comment by lnielsen** [comment]
Closing as first we need these fields in the deposit form.
