### ISSUE TITLE
Support less specific dates

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/invenio-rdm-records#68]
When dealing with historic material, dates are not always known to an accuracy of a specific day.

Would it be possible to support YYYY / YYYY-MM (and even, dare I ask -MM-DD) both in publication_date, and the general dates?

**Comment by fenekku** [comment]
Definitely something we do want to do in some fashion.

Our institution has special materials that need this too.

**Comment by ppanero** [comment]
@fenekku this can be achieved/has been done as part of the EDTF lvl0. No? (Ok, not the `-MM-DD´tho, but the rest).

**Comment by fenekku** [comment]
@ppanero @dfdan Yes, this has been in part addressed by https://github.com/inveniosoftware/invenio-rdm-records/pull/79 . 

- publication_date: is a EDTF level 0 date now. So it supports YYYY-MM-DD, YYYY-MM, YYYY and all interval combinations of the previous (e.g. 1999/20001-10-02 for 1999 to October 2nd 2001) 
- General dates (`dates` field) have a `start_date` and `end_date` (ISO 8601).

Is that combination enough for now? Only "MM-DD" would be missing... but if you have a guess at the year you can enter those as `publication_date` EDTF intervals or `dates`'s  `start_date` `end_date` intervals.

If that works for you, I will mark this as closed via #79 .

**Comment by fenekku** [comment]
Thanks! Closed via #79
