### ISSUE TITLE
vocabularies: integrate affiliations with rdm data model

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#680]
**Data layer**

- [x] Define relation in CommonFIeldsMixin.
    - [x] Determine which fields to dump in ES index.
- [x] JSONShema: Do not modify an already released schema, create new version instead.
- [x] JSONSchema: Define or review existing property
    - List or single?
    - Mixed linked with non-linked?
- [x] Mappings adapt to JSONSchema and dumped fields.

**Service layer**

- [x] Schema: Fix metadata schema.
- [x] Facets: Do we need facets?

**Presentation layer**

- [x] Fix REST API serializations
- [x] Fix other serialization formats.

**Tests**

- [x] Add tests that record linking is wokring as expected (e.g. from service layer).
    - Bad and good data.
- [x] Add REST API tests for serialization, facets
- [x] Ensure that I18N is tested properly if required.

**Comment by ppanero** [comment]
Discusses IRL
> Ensure that I18N is tested properly if required.

No i18n, UI will display `name`.
