### ISSUE TITLE
vocabularies: affiliations loading

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#681]
**Fixtures**

- [x] Add a loader in ``fixtures/<name-plural>.py``
- [x] Add data (may need to see if we distribute or download) -  large vocabs need special loading.
    - Minimal demo data should be provided.

Related to #680

Download data from https://figshare.com/collections/ROR_Data/4596503/7

Basic attempt of parser in https://gist.github.com/ppanero/ef9848e848de16bdb280ef5209f4c6fa

**Comment by ppanero** [comment]
Using Data Dump 8.0 from v9 (April 2021)
