### ISSUE TITLE
serialisers: data cite should read all affiliation in one go

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#716]
Affiliations are being read one by one:

```python
    def _read_affiliation(self, id_):
        """Retrieve affiliation record using service."""
        affiliations_service = (
            current_service_registry.get("rdm-affiliations")
        )
        return affiliations_service.read(id_, system_identity)
```

Instead, we should either

1) Dereference all the needed information into the record JSON so it's available, 
or
2) In the schema ``pre_dump`` collect all affiliation ID's and make a single ``read_many`` query to get all affiliations in one go.

**Comment by ppanero** [comment]
This was part of https://github.com/inveniosoftware/invenio-rdm-records/pull/704, which didn't get done yet. There was a card in the ToDo (I'm deleting it in favour of this issue.
