### ISSUE TITLE
Change preview box filename when previewed file is changed 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#74]
Steps to reproduce:
1- visit a record page with multiple attachments
2- click to preview a different file
expect
3- previewed filename to be showed at top of box
get
3- initially previewed file's name (it doesn't change)

**Comment by dfdan** [comment]
I have (possibly in error) raised this here too https://github.com/inveniosoftware/invenio-previewer/issues/110

**Comment by fenekku** [comment]
closed by https://github.com/inveniosoftware/invenio-app-rdm/issues/735
