### ISSUE TITLE
Validation errors don't get passed for resource_type

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-rdm-records#76]
Typically when one creates a record with an incorrect field a validation error with helpful message is returned:

e.g. `'titles': [{'title': 'A Romans story', 'type': 'Otherss', 'lang': 'eng'}]` returns an errors field that includes `Invalid title type. Otherss not one of MainTitle, AlternativeTitle, Subtitle, TranslatedTitle, Other`

However when one provides an incorrect resource_type in either the type or subtype field no errors field is returned:

e.g.  `'resource_type': {'type': 'imagess', 'subtype': 'photo'}` only returns `{"status": 400, "message": "Validation error."}`

**Comment by fenekku** [comment]
@tmorrell To double-check: is the main issue the helpful list or a missing message in 'errors' ?

**Comment by tmorrell** [comment]
Main issue is not having a helpful list. It’s hard to figure out what the accepted values are (in the schema, marshmallow, somewhere else?)

On Mar 23, 2020, at 2:07 PM, fenekku <notifications@github.com> wrote:

﻿

@tmorrell<https://github.com/tmorrell> To double-check: is the main issue the helpful list or a missing message in 'errors' ?

**Comment by fenekku** [comment]
Got it. Thanks!
