### ISSUE TITLE
datacite: ISNI linking

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-rdm-records#775]
I think this is somewhere in the data layer, as opposed to being a direct datacite serialization issue

## Describe the bug
When an ISNI is entered, it's URL version is the DataCite output is missing a slash

## Steps to Reproduce
1. Enter 0000000054257574 as a name identifier in the deposit form
2. Publish
3. The normal JSON output is fine: "identifier": "0000000054257574", "scheme": "isni"
4. Look at DataCite JSON output:"nameIdentifier": "https://isni.org0000000054257574"

## Expected behavior

"nameIdentifier": "https://isni.org/0000000054257574"

**Comment by lnielsen** [comment]
I think we have solved this issue when we also solved a related issue with ORCIDs. Now it's:

![Screenshot 2021-08-04 at 22 50 32](https://user-images.githubusercontent.com/1698163/128253000-f85fdc9f-99e8-44f2-8dac-01e6740a507b.png)

**Comment by tmorrell** [comment]
Yup, this is fixed in v6
