### ISSUE TITLE
Subjects are improperly aggregated

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#798]
Package version (if known): 6.0

## Describe the bug
When depositing a record and adding different subjects (subject and custom keyword triggers this too), the subjects are not aggregated correctly leading to a subject SUB1 of scheme SCHA to be found in the search aggregation for SCHB.   

## Steps to Reproduce
Make sure to have "subject_nested" in RDM_SEARCH of invenio.cfg:  

```python
RDM_SEARCH = {
    "facets": ["access_status", "resource_type", "subject_nested"],
    'sort': ['bestmatch', 'updated-desc', 'updated-asc', 'newest', 'oldest',
             'version'],
}
```

1. Go to 'uploads/new'
2. Fill valid record with an official subject and a custom keyword
3. Save and publish
4. Go to search page and see incorrect nesting

## Expected behavior

Custom keywords should either not show on the facets or show under separate Keywords category.

## Screenshots (if applicable)

![keyword_faceting_bug](https://user-images.githubusercontent.com/1932651/128519794-037a5cf8-0403-4c73-9b5a-4ad373a414ce.jpg)

![image](https://user-images.githubusercontent.com/1932651/139855285-b5eb96ca-1669-406f-a965-8150cf08c915.png)

## Additional context

Another report of the problem: https://discord.com/channels/692989811736182844/724974365451747329/904931242854727771

**Comment by fenekku** [comment]
still applicable

**Comment by paolap** [comment]
Hi, just wondering if anyone is looking this issue :-)

Thanks

**Comment by fenekku** [comment]
Not at the moment, but thanks for voicing your interest; it will help advocate for tackling this sooner.

**Comment by fenekku** [comment]
We are also seeing schemes not being registered properly e.g., selecting the scheme LCNAF, adding a subject from that scheme and then a keyword results in the subject being added to the keyword section instead of the subject subsection.

**Comment by paolap** [comment]
Hi, just checking if there's any progress on this, I can see that now we could potentially bypass the subjects and use custom fields instead, but if this feature will be working in the new version we could avoid defining additional fields.
Many thanks!

**Comment by fenekku** [comment]
Related PRs:

- invenio-records-resources: https://github.com/inveniosoftware/invenio-records-resources/pull/546
- invenio-rdm-records: to come
