### ISSUE TITLE
Store the content-type (filename pattern maybe) on the serializer

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#817]
From Export serialization https://github.com/inveniosoftware/invenio-app-rdm/pull/1097 (but highlighting an idea originally introduced a long time ago here: https://github.com/inveniosoftware/flask-resources/issues/73): it would make sense to group content-type and serializer together since a serializer knows what kind of content-type it is generating.

In the long run, this could simplify a lot of configuration that duplicates content-type and serializer separately e.g. 
```
response_handlers={
    'application/json': ResponseHandler(JSONSerializer())
},
```
to
```
response_handlers=[
    ResponseHandler(JSONSerializer())
],
```

**Comment by lnielsen** [comment]
There might not be a 1-to-1 mapping of mimetype and serialiser so I would leave it as is.
