### ISSUE TITLE
publisher required for DataCite DOI registration

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-rdm-records#819]
Package version (if known):

## Describe the bug
DataCite requires the record to have a publisher defined. When acquiring a DOI through the "Get DOI" button, the publisher field is not checked. If left empty, no DOI can be acquired and no error is presented.

## Steps to Reproduce
1. Create a new upload
2. Select 'No' on "Do you already have a DOI for this upload?"
3. Fill out all required fields
4. Remove text from publisher field
5. Save draft
6. Publish record

## Expected behavior
An error message is shown, that the publisher has to be defined for the DOI registration.

## Screenshots (if applicable)
![Screenshot from 2021-10-11 11-06-01](https://user-images.githubusercontent.com/72449192/136764414-b9985292-9338-4ff2-b283-bc9d4d818949.png)

**Comment by fenekku** [comment]
The publisher-less DOI record is then marked as "Draft" in Datacite's dashboard which makes sense but adds to the confusion for unfamiliar user.

**Comment by fenekku** [comment]
Closed via https://github.com/inveniosoftware/invenio-rdm-records/pull/1146
