### ISSUE TITLE
"Get DOI now" button requires draft to be saved first

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#856]
Package version (if known): 7.0.1

## Steps to Reproduce
1. Go to https://127.0.0.1:5000/uploads/new 
2. Click on 'Save draft'
3. Select "No" to "Do you already have a DOI for this upload?"
4. Click "Get DOI now!"

See that 

An error is reported: "A PID already exists for type doi".

## Expected behavior

A DOI should be created and no error reported

## Screenshots (if applicable)

![Screenshot 2021-12-09 at 16 31 12](https://user-images.githubusercontent.com/1698163/145425841-fcaa0230-be8d-4768-af00-fbb49f1e03ea.png)

**Comment by chriz-uniba** [comment]
I'm able to reproduce it in v8.

**Comment by lnielsen** [comment]
Yes, we have not yet fixed the issue
