### ISSUE TITLE
Tests make requests to DataCite servers

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#866]
Package version (if known): v0.33.0+

## Describe the bug
The test suite is very slow (`476 passed, 559 skipped, 666 warnings in 615.66s (0:10min15sec)` on my local machine) and upon inspection calls to datacite service are being made during tests. 

For example: `invenio-rdm-records/tests/resources/test_serialized_links.py` makes a call to register a public DOI for each test where the record is published. 

This pattern occurs more widely for every test that publishes, deletes, updates (published) records.

## Expected behavior
Not make external network calls during tests to speed up their execution and not mistakenly make remote changes.

## Sugested solution

Make a fake DOI provider and use it in all tests, so that it mimics the DataCite API while not making external calls.

**Comment by tmorrell** [comment]
These mock tests are already used in the datacite library here https://github.com/inveniosoftware/datacite/blob/master/tests/test_rest.py, and can probably be reused.
