### ISSUE TITLE
Adjust the owners structure in the parent records' access field

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-rdm-records#873]
From https://github.com/inveniosoftware/invenio-records-resources/pull/296 

We should probably adjust the owners structure in the parent records' access field (https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/systemfields/access/owners.py) to use the newly created mechanisms

**Comment by lnielsen** [comment]
Closing as it's similar to #523, and will be revisited once we look into sharing a record
