### ISSUE TITLE
DataCite metadata formats on OAI-PMH

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#880]
See [comment](https://github.com/inveniosoftware/product-rdm/issues/27#issuecomment-1009793303)

**Comment by mitsosf** [comment]
Two PRs

invenio-oaiserver: [213](https://github.com/inveniosoftware/invenio-oaiserver/pull/213)
invenio-app-rdm: [1205](https://github.com/inveniosoftware/invenio-app-rdm/pull/1205)

The config in invenio-oaiserver is overwritten by the config in invenio-app-rdm.
