### ISSUE TITLE
vocabularies: add ROR Aliases

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-rdm-records#933]
## Is your feature request related to a problem? Please describe.
Organizations can have multiple names that are correct (e.g. Caltech and California Institute of Technology). ROR has an `aliases` field that includes alternative names that an organization goes by. 

## Describe the solution you'd like
Users should be able enter either the official ROR name or aliases when searching for affiliations. All should map to the same vocabulary entry with the correct ROR. 

## Describe alternatives you've considered
I could put the alias value into existing acronym field. In the case of Caltech no one uses the CIT acronym, so it's not really needed. This probably wouldn't work for all organizations, and would mean that the data structure isn't the same as ROR.

**Comment by lnielsen** [comment]
Ping @slint

**Comment by tmorrell** [comment]
In v2 ROR puts all possible names in a `name` field https://ror.readme.io/v2/docs/data-structure#names. We should index all possible names. The primary display name will be indicated with the `type` `ror_display`

**Comment by tmorrell** [comment]
Will be fixed by https://github.com/inveniosoftware/invenio-vocabularies/pull/327

**Comment by slint** [comment]
https://github.com/inveniosoftware/invenio-vocabularies/pull/327 is merged so closing this
