### ISSUE TITLE
cli: communities demo data not working

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-rdm-records#957]
Package version (if known): 0.35.10

## Describe the bug
The command `invenio rdm-records demo communities` is throwing an error.

## Steps to Reproduce
1. Launch the following command `invenio rdm-records demo communities`.
2. See error. 

## Expected behavior
To create demo data for the communities

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/166887139-f18b58d6-6090-4d41-9668-3332b2cc504a.png)

**Comment by ntarocco** [comment]
The change (add `slug`) should happen here: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/demo.py#L318

**Comment by ppanero** [comment]
@jrcastro2 is this still happening? I couldnt reproduce with latest rdm-records/communities

**Comment by jrcastro2** [comment]
> @jrcastro2 is this still happening? I couldnt reproduce with latest rdm-records/communities

The version I had when this was failing was `0.35.10` if you tried with a newer version and it works I guess you can close the issue.

**Comment by ppanero** [comment]
After running the command with `0.35.11` and communities `2.8.0.dev20` the communities are displayed

![Screenshot 2022-05-10 at 09 59 17](https://user-images.githubusercontent.com/6756943/167578778-ed4eb2c2-325f-4986-8e5a-cd3f986339e1.png)
