### ISSUE TITLE
AttributeError: 'UIJSONSerializer' object has no attribute 'serialize_object_to_dict'

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-rdm-records#988]
Package version (if known): 02cc228a94b56f299c3a78e44679ad4e79ab34a0

## Describe the bug
Building from the latest master, when you click search and open one of the results will lead to AttributeError: 'UIJSONSerializer' object has no attribute 'serialize_object_to_dict'

## Steps to Reproduce
1. run invenio
2. Click on serach
3. click on any result
4. See error AttributeError: 'UIJSONSerializer' object has no attribute 'serialize_object_to_dict'

## Expected behavior
open the result

## Additional context
I notice that serialize_object_to_dict is been removed so if I replace it with serialize_object_list in  venv/lib/python3.9/site-packages/invenio_app_rdm/records_ui/views/records.py L80 
then  I will get Page not found

**Comment by zzacharo** [comment]
issue was fixed in https://github.com/inveniosoftware/invenio-app-rdm/pull/1706
