### ISSUE TITLE
Potential dependency conflicts between invenio-rdm-records and invenio-records-files

### ISSUE THREAD

**Issue by NeolithEra** [inveniosoftware/invenio-rdm-records#99]
Hi, as shown in the following full dependency graph of **_invenio-rdm-records_**, **_invenio-rdm-records_** requires **_invenio-records-files >=1.2.1,<1.3.0_**, **_invenio-rdm-records_** requires **_invenio-records-permissions >=0.7.0_** (**_invenio-records-permissions 0.7.0_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_invenio-records-permissions 0.7.0_** transitively introduces **_invenio-records-files >=1.2.0,<1.3.0_**.

Obviously, there are multiple version constraints set for **_invenio-records-files_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_invenio-records-files 1.2.1_** (i.e., the newest version satisfying constraint **_>=1.2.1,<1.3.0_**) is the actually installed version.

Although the first found package version **_invenio-records-files 1.2.1_** just satisfies the later dependency constraint （**_invenio-records-files >=1.2.1,<1.3.0_**), such installed version is very close to the upper bound of the version constraint of invenio-records-files specified by **_invenio-records-permissions 0.7.0_**. 

Once **_invenio-records-permissions_** upgrades，its newest version will be installed, as **_invenio-rdm-records_** does not specify the upper bound of version constraint for **_invenio-records-permissions_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_invenio-records-permissions_** version introduces a higher version of **_invenio-records-files_**, violating its another version constraint **_>=1.2.1,<1.3.0_**.

According to the release history of invenio-records-permissions, it habitually upgrates Invenio-records-files in its recent releases. For instance, invenio-records-permissions 0.7.0 upgrated Invenio-records-files’s constraint from _* to ==1.1._ , and invenio-records-permissions 0.7.1 upgrated Invenio-records-files’s constraint from **_==1.1.1 to >=1.2.0,<1.3.0_**. 

As such, it is a warm warning of a potential dependency conflict issue for invenio-rdm-records.

### Dependency tree
```
invenio-rdm-records - 2.0.1
| +- jsonmerge(install version:1.7.0 version range:>=1.4.0,<2.0)
| | +- jsonschema(install version:2.6.0 version range:*)
| +- jsonschema(install version:2.6.0 version range:<3.0.0)
| +- invenio-records-permissions(install version:0.7.0 version range:>=0.7.0)
| | +- invenio-records-files(install version:1.2.1 version range:>=1.2.0,<1.3.0)
| | +- pyserial(install version:3.4 version range:==3.)
| | +- six(install version:1.14.0version range:==1.)
| +- invenio-records-files(install version:1.2.1 version range:>=1.2.1,<1.3.0)
| | +- mbed-os-tools(install version:0.0.13 version range:>=0.0.9,<0.1.0)
| | +- prettytable(install version:0.7.2 version range:>=0.7.2)
| +- prettytable(install version:0.7.2 version range:<1.0)
| +- pydash(install version:4.7.6 version range:<5.0,>=4.0)
| +- pyserial(install version:3.4 version range:>2.5)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- semver(install version:2.10.1 version range:<3.0,>=2.0)
| +- six(install version:1.14.0 version range:>=1.0,<2.0)
| +- transitions(install version:0.8.1 version range:<1.0)
| | +- six(install version:1.14.0 version range:*)
| +- yattag(install version:1.13.2 version range:>=1.0,<2.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_invenio-records-files_** to be **_>=1.2.1_**.
2.	Remove your direct dependency **_invenio-records-files_**, and use the **_invenio-records-files_** transitively introduced by **_invenio-records-permissions_**.
3.	Change your direct dependency **_invenio-records-permissions_** to be **_<=0.7.0_**.
@ppanero  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by lnielsen** [comment]
Thanks @NeolithEra for reporting. All the modules you mention are under our control, and when we're out of the development phase, InvenioRDM will control the dependencies via Invenio releases, which locks all related modules to their patch-level release.  Thus, this is not something we will fix at this stage of the development. Thanks though for the offer to make a PR, it's much appreciated!
